### ISSUE TITLE
[gimie] Implement missing github API fields

### ISSUE THREAD

**Issue by cmdoret** [SDSC-ORD/gimie#26]
A GithubExtractor is already implemented in gimie, but it does not extract all relevant fields provided by the API.
Namely, the following fields remain to be implemented:

**Requirements:**

> Below are proposed mappings. the Notation is `"github_variable_name"` → `namespace:property`

On `schema:SoftwareSourceCode`:
+ [x] `"language"` → `schema:programmingLanguage`
+ [x] `"html_url"` → `schema:codeRepository`
+ [x] "`releases_url">[0]["name"]` → `schema:softwareVersion`
+ [x] `"releases_url">[0]["body"]` → `schema:releaseNotes`
+ [x] `"topics"` → `schema:keywords`
+ [ ] Bonus: `"stargazer_count"` →❓

On `schema:Person`:
+ [x] `"login"` → `schema:identifier` or `❓:githubUsername`
+ [x] `"name"` → `schema:name` and drop

On `schema:Organization`:
+ [x] `"name"` → `schema:legalName`
+ [x] `"login"` → `schema:name`
+ [x]  `"avatar_url"` → `schema:logo`
+ [x] `"description"` → `schema:description`

**Comment by cmdoret** [comment]
@rmfranken Do you have any other suggestions ? (especially regarding the 2 ❓)

**Comment by rmfranken** [comment]
Sorry, totally forgot to respond to this. I think stargazer_count is something we can leave out: There's no schema.org property for it, and it does not provide much value I think. And is not part of the imaging plaza properties either.

For a person, the github username is a bit spicier. A github username is unique, but if that user deletes their account, the username can be taken again after 90 days by someone else. This could mean that if your data is referencing some username, after 90 days that triple can point towards an entirely different entity, which is not a good property of an "identifier". I see two options:
- Accept the risk of lack of persistence on :identifier since deleting a github account is probably quite a rare occurrence (software engineering is still too young of a profession for the people doing it to die or retire often, so we are pushing this problem forward to like 2050, when we all the 1970's born people start dying en masse)
- use a custom property (although the persistence problem remains, but can be a bit reduced by adding the limitation of the property in the definition ("This property identifies a gitHub user at the time of extraction and is informative. Github usernames are not persistent" or something like that))
- don't use the githubUsername at all

All three are very valid options imo.

**Comment by cmdoret** [comment]
Thanks @rmfranken I dropped stargazer_count.

The GitHub username is still useful, as this is how you find somebody. However, GitHub also provides an `id` field, which, I believe, is persistent. (e.g.  `22558602` for me).

How about this for `sh:Person`?
`sh:identifier` -> `22558602`
`gimie:githubUsername` -> `cmdoret`
`sh:name` -> `Cyril Matthey-Doret`

> Not sure if it makes sense to use a `gimie:` prefix for `githubUsername`

**Comment by rmfranken** [comment]
>sh:identifier -> 22558602
gotta be careful, sh: is the namespace for the SHACL spec, so this is always describing the ontology/schema. schema: is what you meant I guess. In that case, that would work well.
>gimie:githubUsername -> cmdoret
yes, I think it makes sense. A quick google search has not yielded a nice "Git" ontology, so I think it's fair we create this property ourselves.
>sh:name
This is a valid shacl property, but it is to indicate the name of a property, not the name of an object you are describing. Although it's a little bit silly (the meaning of "name" should not change depending on the namespace that uses it) I think you mean schema:name here.

**Comment by cmdoret** [comment]
Right, I should have used `schema` instead of `sh` :grin: 
OK, maybe _for now_ a non-persistent :identifier should be OK, and this would avoid having to develop a separate ontology.

```ttl
<https://api.github.com/users/cmdoret> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD>,
        <https://api.github.com/orgs/SwissDataScienceCenter>,
        <https://api.github.com/orgs/koszullab> ;
    schema:identifier "cmdoret" ;
    schema:name "Cyril Matthey-Doret" .
```
